### ISSUE TITLE
Latest image probably does not work with docker 1.12.0

### ISSUE THREAD

**Issue by melkor217** [edyn/docker-docker-stats-statsd#2]
```
[dan@dan-desktop ~]$ docker -v
Docker version 1.12.0, build 8eab29e
[dan@dan-desktop ~]$ docker-compose -v
docker-compose version 1.8.0-rc2, build c72c966
```

It just spams undefined values to statsd:

```
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_noxus_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_noxus_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_ayanami_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_ayanami_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_lb_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_lb_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_mysql_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_mysql_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_redis_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_redis_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_graphite_1.cpu.cpu_percent:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_graphite_1.memory.total_swap:undefined|g"
29 Jul 23:10:08 - DEBUG: Bad line: undefined,g in msg "docker.ayanami_workers_1.cpu.cpu_percent:undefined|g"
```

I run it via docker-compose like this:

```
  stats:
    image: edyn/docker-stats-statsd:latest
    privileged: true
    environment:
      STATSD_HOST: graphite
      STATSD_PORT: 8125
      STATSD_PREFIX: docker.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - graphite
```
